config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :movies
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
  resources :rails_texts
  resources :questions
  resources :questions do
    resources :solutions, only: [:create]
  end

  resources :aws_texts, only:["index", "show"]
  resources :line_texts, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
end

app/models/line_text.rb
class LineText < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :body, :title, presence: true
end

app/models/rails_text.rb
class RailsText < ApplicationRecord

end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question

  validates :answer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end
end

app/controllers/line_texts_controller.rb
class LineTextsController < ApplicationController
  def index
    @line_texts = LineText.all
  end

  def show
    @line_text = LineText.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    if params[:category]
      @movies = Movie.where(category: params[:category]).page(params[:page]).per(10)
    else
      @movies = Movie.where(category: ["Basic", "Git", "Ruby", "Ruby on Rails"]).page(params[:page]).per(10)
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @question = Question.new
    @questions = Question.all
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash.notice = "質問を投稿しました。"
      redirect_to action: :index
    else
      flash.now[:alert] = "内容が入力されていません。"
      @questions = Question.all
      render :index
    end
  end

  def show
    @question = Question.find(params[:id])
    @solutions = @question.solutions.all
    @solution  = @question.solutions.new
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/controllers/rails_texts_controller.rb
class RailsTextsController < ApplicationController
    before_action :authenticate_user!
  def index
    @rails_texts = RailsText.all
  end

  def show
    @rails_text = RailsText.find(params[:id])
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  def create
    @question = Question.find_by(id: params[:question_id])
    @solution = @question.solutions.build(solution_params)

      if @solution.save
          redirect_to question_path(@question.id)
          flash[:notice] = "回答を投稿しました"
      else
        @solutions = Solution.all
        render "questions/show"
        flash.now[:alert] = "【回答】は空欄にできません"
       end

    end


    private
    def solution_params
      params.require(:solution).permit(:answer)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

end

def nav_color
    controller_name == 'line_texts' ?  '#28a745' : '#5C99FF'
  end

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.present?

      case language.to_s
      when 'rb'
        lang = :ruby
      when 'yml'
        lang = :yaml
      when 'css'
        lang = :css
      when 'html'
        lang = :html
      when ''
        lang = :md
      else
        lang = language
      end

        CodeRay.scan(code, lang).div
    end

  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" }
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/line_texts_helper.rb
module LineTextsHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rails_texts_helper.rb
module RailsTextsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/aws_texts/index.html.erb
<div class="container aws-container">
 <div>
   <h1 class="text-center">AWS講座</h1>
   <p>注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>
 </div>
 <table class="table table-striped">
   <thead class="aws-thead">
     <tr>
       <th scope="col aws-index">No.</th>
       <th scope="col">内容</th>
     </tr>
   </thead>
   <tbody>
     <% @aws_texts.each do |aws_text|  %>
             <tr>
               <th scope="row" class="aws-index"><%= aws_text.id %></th>
               <td class="aws-title"><%= link_to aws_text.title, aws_text_path(aws_text.id)%></td>
             </tr>
           <% end  %>
   </tbody>
 </table>

</div>

app/views/aws_texts/show.html.erb
<div class="container aws-content mx-auto">
  <%= markdown(@aws_text.content).html_safe %>
</div>

app/views/line_texts/index.html.erb
<div class="container line-container">
  <h2 class="text-center text-success">LINE@</h2>
  <div class="table-container">
     <table class="table table-striped">
     <thead class="bg-success text-white">
      <tr>
        <th class="w-1">No.</th>
        <th class="w-2">ジャンル</th>
        <th class="w-5">内容</th>
      </tr>
    </thead>
    <tbody>
      <footer class='<%= "#{controller.controller_name}" %>'>
      <% @line_texts.each.with_index(1) do |line_text, i|  %>
      <tr>
        <td><%= i %></td>
        <td><%= line_text.genre %></td>
        <td><%= link_to line_text.title, line_text_path(line_text.id), target: "_blank" %></td>
     </tr>
     <% end %>
    </tbody>
  </table>
  <nav class="navbar navbar-expand navbar-dark fixed-bottom justify-content-center" style="background-color:#28a745;">

  	<ul class="navbar-nav">
  		<li nav-item><a href="#" class="nav-link active">ブログ</a></li>
  		<li nav-item><a href="#" class="nav-link active">youtube</a></li>
  	</ul>
  </nav>
  <%= yield :footer %>
</div>

app/views/line_texts/show.html.erb
<div class="container line-content mx-auto">
  <%= markdown(@line_text.content).html_safe %>
  <%= yield :footer %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h1>新規投稿</h1>

  <%= form_with model: @question, method: :post, local: true do |f|%>

    <div class='form-group'>
      <%= f.label :title, "【質問】", for: 'question_title' %>
      <%= f.text_area :title, class:'form-control', id: 'question_title', rows: '3'%>
    </div>

    <div class='form-group'>
      <%= f.label :body, "【詳細】", for: 'question_body' %>
      <%= f.text_area :body, class:'form-control', id: 'question_body', rows: '5'%>
    </div>

    <div class="form-group">
      <%= f.submit '送信', class: "btn btn-primary btn-block btn-lg", data: {confirm: "新規登録しますか？"} %>
    </div>

  <% end %>


  <% @questions.each do |question| %>

    <div class="question py-5 row ">

      <div class="col-7">
        <p><%= link_to question.title, question_path(question.id)  %></p>
      </div>

      <div class="col-5 text-right">
        <p>質問日　<%= l(question.created_at) %></p>
      </div>

    </div>

  <% end %>

</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="border-bottom">
    <p>【質問】</p>
    <p><%= @question.title %></p>
  </div>
  <div class="border-bottom mt-5">
    <p>【詳細】</p>
    <p><%= markdown(@question.body).html_safe %></p>
  </div>
  <div class="mt-5">
    <% @solutions.each do |solution|  %>
      <p>【回答】</p>
      <div class="border-bottom my-5">
        <p><%= markdown(solution.answer).html_safe %></p>
      </div>
    <% end  %>
  </div>

  <div class="container">
    <h1>回答投稿</h1>

    <% if @solution.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @solution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: [@question, @solution], local: true do |f| %>

  <div class="form-group">
        <%= f.label :answer, '【回答】' %>
        <%= f.text_area :answer, class: 'form-control', rows:10 %>
    </div>

  <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg", data: {confirm: "投稿しますか？"} %>
      </div>

 <% end %>
</div>

app/views/rails_texts/index.html.erb
<div class="cover text-center">
  <div class="rails_texts-wrapper">
  <div class="contents-title">
      <%= render "layouts/search_rails_text" %>
    <h2>テキスト教材</h2>
  </div>

  <div class="row">
    <div class="rails_texts-contents">
    <% @rails_texts.each do |rails_text| %>
    </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="rails_texts-content">
        <%= link_to rails_text_path(rails_text.id), {:target => "_blank"} do %>
          <h3><%= rails_text.title %></h3>
          <p><%= "【#{rails_text.genre}】" %></p>
          <% end %>
     </div>
     <% end %>
    </div>
  </div>
  </div>

app/views/rails_texts/show.html.erb
<div class="container rails-content mx-auto">
  <%= markdown(@rails_text.content).html_safe %>
  <%= yield :footer %>
</div>