config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :movies
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
  resources :rails_texts
  resources :questions
  resources :questions do
    resources :solutions, only: [:create]
  end

  resources :aws_texts, only:["index", "show"]
  resources :line_texts, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
end

app/models/line_text.rb
class LineText < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :body, :title, presence: true
end

app/models/rails_text.rb
class RailsText < ApplicationRecord

end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question

  validates :answer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end
end

app/controllers/line_texts_controller.rb
class LineTextsController < ApplicationController
  def index
    @line_texts = LineText.all
  end

  def show
    @line_text = LineText.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    if params[:category]
      @movies = Movie.where(category: params[:category]).page(params[:page]).per(10)
    else
      @movies = Movie.where(category: ["Basic", "Git", "Ruby", "Ruby on Rails"]).page(params[:page]).per(10)
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @question = Question.new
    @questions = Question.all
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash.notice = "質問を投稿しました。"
      redirect_to action: :index
    else
      flash.now[:alert] = "内容が入力されていません。"
      @questions = Question.all
      render :index
    end
  end

  def show
    @question = Question.find(params[:id])
    @solutions = @question.solutions.all
    @solution  = @question.solutions.new
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  def create
    @question = Question.find_by(id: params[:question_id])
    @solution = @question.solutions.build(solution_params)

      if @solution.save
          redirect_to question_path(@question.id)
          flash[:notice] = "回答を投稿しました"
      else
        @solutions = Solution.all
        render "questions/show"
        flash.now[:alert] = "【回答】は空欄にできません"
       end

    end


    private
    def solution_params
      params.require(:solution).permit(:answer)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

end

def nav_color
    controller_name == 'line_texts' ?  '#28a745' : '#5C99FF'
  end

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.present?

      case language.to_s
      when 'rb'
        lang = :ruby
      when 'yml'
        lang = :yaml
      when 'css'
        lang = :css
      when 'html'
        lang = :html
      when ''
        lang = :md
      else
        lang = language
      end

        CodeRay.scan(code, lang).div
    end

  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" }
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/line_texts_helper.rb
module LineTextsHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rails_texts_helper.rb
module RailsTextsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand navbar-dark fixed-bottom justify-content-center" style="background-color: <%= nav_color  %>">
	<ul class="navbar-nav">
		<li nav-item><a href="#" class="nav-link active">ブログ</a></li>
		<li nav-item><a href="#" class="nav-link active">youtube</a></li>
	</ul>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: <%= nav_color  %>">
  <%= link_to "Gyakuten", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav1" aria-controls="nav1" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-around" id="nav1">
    <ul class="navbar-nav">
      <li class="nav-item dropdown"><a href="#" class="nav-link dropdown-toggle active" data-toggle="dropdown">Rails</a>
        <div class="dropdown-menu">
          <%= link_to "動画教材", root_path, class: "dropdown-item", style: "color: #5C99FF" %>
          <%= link_to "テキスト教材", rails_texts_path, class: "dropdown-item", style: "color: #5C99FF" %>
          <%= link_to "ライブコーディング", root_path(category: "Live"), class: "dropdown-item", style: "color: #5C99FF" %>
          <a href="/questions" class="dropdown-item" style="color:#5C99FF">質問集</a>
        </div>
      </li>
      <li class="nav-item"><%= link_to "AWS講座", aws_texts_path, class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to "PHP講座", root_path(category: "Php"), class:"nav-link active" %></li>
      <li class="nav-item"><%= link_to "対談", root_path(category: "Talk"), class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to "情報発信", root_path(category: "Marketing"), class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to "動画編集講座", root_path(category: "Movie"), class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to "ライティング講座", root_path(category: "Writing"), class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to "LINE@", line_texts_path, class: "nav-link active" %></li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: 'post nav-link active' %>
          <!--<%= link_to "新規登録", new_user_registration_path, class: 'post' %>-->
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_search_rails_text.html.erb
<form class="mb-3 search-form mx-auto">
  <i class="fa fa-search search-icon" title="Search"></i>
  <input type="text" id="search-rails_text" class='form-control search-rails_text' placeholder="教材を探す" aria-label="Username" aria-describedby="search-form">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup9</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render "layouts/footer" %>

   </body>
</html>